apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maven-webapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hareesh88666/canary
    targetRevision: main
    path: chart

    helm:
      valueFiles:
        - values-canary.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
